INSERT INTO exercises (name, description, muscle_group, difficulty, default_hold_time_or_reps, animation_asset_id)
VALUES
    ('Cat-Cow', 'Spinal mobility movement alternating flexion and extension.', 'Spine', 1, 8, 'cat_cow'),
    ('Child''s Pose', 'Relaxed kneeling stretch for hips and lower back.', 'Hips', 1, 30, 'childs_pose'),
    ('Thread the Needle', 'Thoracic rotation stretch from quadruped.', 'Upper Back', 2, 8, 'thread_the_needle'),
    ('World''s Greatest Stretch', 'Dynamic lunge with rotation for hips and thoracic spine.', 'Full Body', 3, 6, 'worlds_greatest_stretch'),
    ('90/90 Hip Switch', 'Seated hip internal and external rotation drill.', 'Hips', 2, 10, '90_90_hip_switch'),
    ('Couch Stretch', 'Hip flexor stretch using wall or bench support.', 'Hips', 2, 45, 'couch_stretch'),
    ('Ankle Dorsiflexion Rock', 'Knee-to-wall ankle mobility drill.', 'Ankles', 1, 12, 'ankle_dorsiflexion_rock'),
    ('Scapular Wall Slide', 'Shoulder mobility and scapular control drill.', 'Shoulders', 2, 10, 'scapular_wall_slide'),
    ('Supine Twist', 'Gentle spinal rotation stretch.', 'Spine', 1, 30, 'supine_twist'),
    ('Hip Airplane', 'Single-leg hip stability and rotation drill.', 'Hips', 3, 6, 'hip_airplane'),
    ('Seated Straddle Stretch', 'Seated hip adductor stretch with forward hinge.', 'Hips', 1, 45, 'seated_straddle_stretch'),
    ('Pigeon Pose', 'Deep glute and hip external rotation stretch.', 'Glutes', 2, 45, 'pigeon_pose'),
    ('Lunge with Overhead Reach', 'Hip flexor stretch with thoracic extension.', 'Hips', 2, 30, 'lunge_overhead_reach'),
    ('Open Book', 'Side-lying thoracic rotation stretch.', 'Upper Back', 1, 8, 'open_book'),
    ('Standing Quad Stretch', 'Standing quad stretch with balance support.', 'Quads', 1, 30, 'standing_quad_stretch'),
    ('Half-Kneeling Hip Flexor', 'Hip flexor stretch with posterior pelvic tilt.', 'Hips', 2, 40, 'half_kneeling_hip_flexor'),
    ('Glute Bridge Hold', 'Isometric glute bridge for hip extension activation.', 'Glutes', 2, 20, 'glute_bridge_hold'),
    ('Figure Four Stretch', 'Supine glute and piriformis stretch.', 'Glutes', 1, 40, 'figure_four_stretch'),
    ('Crescent Lunge', 'Dynamic lunge to open hips and calves.', 'Hips', 2, 8, 'crescent_lunge'),
    ('Downward Dog', 'Posterior chain stretch for calves and hamstrings.', 'Hamstrings', 2, 30, 'downward_dog'),
    ('Hamstring Sweep', 'Standing hamstring mobility sweep.', 'Hamstrings', 2, 10, 'hamstring_sweep'),
    ('Seated Hamstring Reach', 'Seated hamstring stretch with neutral spine.', 'Hamstrings', 1, 45, 'seated_hamstring_reach'),
    ('Calf Stretch Wall', 'Wall-supported calf stretch.', 'Calves', 1, 30, 'calf_stretch_wall'),
    ('Ankle Circles', 'Controlled ankle mobility circles.', 'Ankles', 1, 12, 'ankle_circles'),
    ('Knee Hugs', 'Standing knee hugs to open hips.', 'Hips', 1, 10, 'knee_hugs'),
    ('Leg Swings Front-Back', 'Dynamic leg swings for hip mobility.', 'Hips', 2, 12, 'leg_swings_front_back'),
    ('Leg Swings Side-to-Side', 'Dynamic lateral leg swings for hip mobility.', 'Hips', 2, 12, 'leg_swings_side_side'),
    ('Deep Squat Hold', 'Bottom squat position to open hips and ankles.', 'Full Body', 3, 30, 'deep_squat_hold'),
    ('Goblet Squat Pry', 'Squat hold with gentle side-to-side pry.', 'Hips', 3, 8, 'goblet_squat_pry'),
    ('Thoracic Extension on Floor', 'Thoracic extension over a rolled towel.', 'Upper Back', 2, 8, 'thoracic_extension_floor'),
    ('Wall Angels', 'Shoulder mobility with back against wall.', 'Shoulders', 2, 10, 'wall_angels'),
    ('Shoulder Dislocates', 'Band pass-throughs for shoulder mobility.', 'Shoulders', 2, 10, 'shoulder_dislocates'),
    ('Sleeper Stretch', 'Posterior shoulder stretch in side-lying.', 'Shoulders', 2, 30, 'sleeper_stretch'),
    ('Wrist Flexor Stretch', 'Gentle wrist flexor stretch.', 'Wrists', 1, 30, 'wrist_flexor_stretch'),
    ('Wrist Extensor Stretch', 'Gentle wrist extensor stretch.', 'Wrists', 1, 30, 'wrist_extensor_stretch'),
    ('Neck Side Glide', 'Lateral neck glide for mobility.', 'Neck', 1, 8, 'neck_side_glide'),
    ('Chin Tucks', 'Deep neck flexor activation.', 'Neck', 1, 10, 'chin_tucks'),
    ('Bird Dog', 'Spine stability with contralateral reach.', 'Core', 2, 8, 'bird_dog'),
    ('Dead Bug', 'Core control with opposite arm/leg extension.', 'Core', 2, 8, 'dead_bug'),
    ('Side Plank Hold', 'Lateral core stability hold.', 'Core', 3, 20, 'side_plank_hold'),
    ('Cobra Press-Up', 'Lumbar extension press-up.', 'Lower Back', 1, 8, 'cobra_press_up'),
    ('Jefferson Curl', 'Segmental spinal flexion with light load.', 'Spine', 4, 6, 'jefferson_curl'),
    ('Quadruped Rock Back', 'Hip hinge pattern from quadruped.', 'Hips', 1, 10, 'quadruped_rock_back'),
    ('T-Spine Rotation Reach', 'Kneeling thoracic rotation with reach.', 'Upper Back', 2, 8, 't_spine_rotation_reach'),
    ('Prone Y-T-W', 'Scapular control through Y-T-W positions.', 'Upper Back', 3, 6, 'prone_y_t_w'),
    ('Bridge Hold', 'Full bridge mobility and shoulder opening.', 'Full Body', 4, 15, 'bridge_hold'),
    ('Hip Flexor Pulse', 'Active hip flexor stretch with pulses.', 'Hips', 2, 12, 'hip_flexor_pulse'),
    ('Adductor Rocking', 'Adductor stretch from all fours.', 'Hips', 2, 10, 'adductor_rocking'),
    ('Spiderman Lunge', 'Dynamic lunge with hip opening.', 'Hips', 2, 8, 'spiderman_lunge'),
    ('Standing Side Bend', 'Lateral chain stretch with overhead reach.', 'Full Body', 1, 30, 'standing_side_bend');
